from selenium.webdriver.common.by import By


class JourneyPageLocators:
    DES_MAKE_YOUR_OFFER = (By.XPATH, '//*[.="Make your offer"]')
    DES_SIGN_AND_SUBMIT = (By.XPATH, '//*[.="Sign and  Submit"]')
    DES_NEGOTIATE = (By.XPATH, '//*[.="Negotiate"]')
    DES_WIN_YOUR_HOME = (By.XPATH, '//*[.="Win Your Home"]')
    DES_OPEN_ESCROW = (By.XPATH, '//*[.="Open Escrow"]')
    DES_CONTINGENCY_PERIOD = (By.XPATH, '//*[.="Contingency Period"]')
    DES_LAST_LOOKS = (By.XPATH, '//*[.="Last Looks"]')
    DES_CLOSING_TIME = (By.XPATH, '//*[.="Closing Time"]')
    GET_CASH_BACK = (By.XPATH, '//*[.="Get Cash Back"]')
    DRAFT_AN_OFFER_BUTTON = (By.XPATH, '//*[.=" Draft an offer "]')
    CASH_BACK = (By.XPATH, '//*[.="Open escrow"]')
    CLOSING_TIME = (By.XPATH, '//*[.="Contingency period"]')
    LAST_LOOKS = (By.XPATH, '//*[.="Last looks"]')
    CONTINGENCY_PERIOD = (By.XPATH, '//*[.="Closing time"]')
    OPEN_ESCROW = (By.XPATH, '//*[.="Open escrow"]')
    WIN_YOUR_HOME = (By.XPATH, '//*[.="Make your offer"]')
    NEGOTIATE = (By.XPATH, '//*[.="Negotiate"]')
    SIGN_AND_SUBMIT = (By.XPATH, '//*[.="Sign and submit"]')
    MAKE_YOUR_OFFER = (By.XPATH, '//*[.="Make your offer"]')
    REFER_ME = (By.XPATH, '//*[.="REFER ME"]')
    CLOSE_X = (By.XPATH, '//*[@alt="close"]')
    REQUEST_HOME_VALUATION = (By.XPATH, '//*[@re2e="searchInputField"]')
    GET_STARTED_BUTTON = (By.XPATH, '//*[.="Get started"]')
    SELL_OPTION = (By.XPATH, '//*[.="Sell"]')
    BUY_AND_SELL_OPTION = (By.XPATH, '//*[.="BUY AND SELL"]')
    LISTING_AGREEMENT = (By.XPATH, '//*[.="Listing Agreement"]')
    REQUEST_VISIT_BUTTON = (By.XPATH, '//*[.=" Request visit "]')
    SELL_YOUR_HOME_OPTIONS = (By.CLASS_NAME, 'sell-your-home__options')
    LISTING_AGREEMENT_TAB = (By.XPATH, '//*[.="Listing agreement"]')
    LISTINGS_PRESENTATION_TAB = (By.XPATH, '//*[.="Listing presentation"]')
    HOME_VALUATION_TAB = (By.XPATH, '//*[.="Home valuation"]')
    HOW_TO_SELL_YOUR_HOME_TAB = (By.XPATH, '//*[.="How to sell your home"]')
    REQUEST_SENT = (By.XPATH, '//*[.=" Request sent "]')
    CONNECT_ME = (By.XPATH, '//*[.=" Connect me "]')
    SCHEDULE_A_TOUR_BUTTON = (By.XPATH, '//*[.=" Schedule a tour "]')
    REQUEST_HOME_VALUATION_BUTTON = (By.XPATH, '//*[.=" Request home valuation "]')
    GET_PRE_APPROVED_BUTTON = (By.XPATH, '//*[.=" Get pre-approved "]')
    STEP_3 = (By.XPATH, '//*[.=" Step 3 "]')
    STEP_1 = (By.XPATH, '//*[.=" Step 1 "]')
    BROWSE_LISTINGS = (By.XPATH, '//*[.="Browse Listings"]')
    TAKE_A_TOUR = (By.XPATH, '//*[.="Take a tour"]')
    GET_HOME_VALUATION = (By.XPATH, '//*[.="Get home valuation"]')
    GET_REALI_VERIFIED = (By.XPATH, '//*[.="Get Reali verified"]')
    SEARCH_FOR_LISTINGS_BUTTON = (By.XPATH, '//*[.=" Search for listings "]')
    JOURNEY_TAB = (By.XPATH, '//*[.="Journey"]')
    STEP_2 = (By.XPATH, '//*[.=" Step 2 "]')
