from selenium.webdriver.common.by import By


class HomesPageLocators:
    HOMES_TAB = (By.XPATH, '//*[.="Homes"]')
    TOASTER = (By.CLASS_NAME, 'cdk-global-overlay-wrapper')
    REALI_LOGO = (By.CLASS_NAME, 'logo-image')
    BUY_TAB = (By.XPATH, '//*[.="Buy"]')
    SELL_TAB = (By.XPATH, '//*[.="Sell"]')
    MORTGAGE_TAB = (By.XPATH, '//*[.=" Mortgage "]')
    SIGN_IN = (By.XPATH, '//*[@re2e="headerSignIn"]')
    RECOMMENDED_DROP_DOWN_MENU = (By.TAG_NAME, 'mat-select-trigger')
    LISTINGS = (By.TAG_NAME, 'rw-listing-card')
    STREET = (By.CLASS_NAME, 'listing-info-location-address')
    CITY = (By.CLASS_NAME, 'listing-info-location-city')
    BEDS_AMOUNT = (By.XPATH, '//*[@re2e="listingCardBeds"]')
    BATHS_AMOUNT = (By.XPATH, '//*[@re2e="listingCardBaths"]')
    SIZE_LISTING_SQUARE_FOOT = (By.XPATH, '//*[@re2e="listingCardSize"]')
    PRICE = (By.XPATH, '//*[@re2e="listingCardPrice"]')
    WAIT = (By.XPATH, '//*[@re2e="beds"]')
    ACTUAL_STREET = (By.CLASS_NAME, 'street')
    ACTUAL_LOCATION = (By.CLASS_NAME, 'location')
    ACTUAL_BEDS = (By.XPATH, '//*[@re2e="beds"]')
    ACTUAL_BATHS = (By.XPATH, '//*[@re2e="baths"]')
    ACTUAL_SIZE = (By.XPATH, '//*[@re2e="houseSize"]')
    ACTUAL_PRICE = (By.CLASS_NAME, 'listing-summary-price')
    HEADER = (By.TAG_NAME, 'header')
    SEARCH_BADGE = (By.TAG_NAME, 'rw-search-autocomplete')
    SEARCH_INPUT_FIELD = (By.XPATH, '//*[@re2e="searchInputField"]')
    SEARCH_RESULT = (By.XPATH, '//*[@re2e="searchResults"]')
    FEED_SORT_DROP_DOWN_MENU = (By.XPATH, '//*[@re2e="feedSortBtn"]')
    MAT_OPTIONS = (By.CLASS_NAME, 'mat-option-text')
    OPTION_LIST = ['Recommended', 'Lowest Price', 'Highest Price', 'Distance (Near-Far)', 'Upcoming Open Houses',
                   'Largest Homes', 'Newest', 'Most Bedrooms']
    USER_ICON = (By.XPATH, '//*[@re2e="headerUserIcon"]')
    BEDS_OPTION = (By.XPATH, '//*[.=" Most Bedrooms "]')
    LISTINGS_CARDS = (By.TAG_NAME, 'rw-listing-card')
    SIDE_NAV_BAR_HOMES = (By.TAG_NAME, 'rw-side-navigation')
    FAVORITE_ICON = (By.CLASS_NAME, 'listing-info-favorite')
    CANCEL_X = (By.XPATH, '//*[.="cancel"]')
